---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: update repository index (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

- hosts: ubuntu_prometheus
  become: true
  roles:
    - ubuntu_prometheus

- hosts: centos_prometheus
  become: true
  roles:
    - centos_prometheus

